import { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import Eightballjs from "../components/Eightballjs";
import ERC1155ABI from "../contracts/eightBall.json";
import styles from "../styles/Home.module.css";
import type { NextPage } from "next";
import { useAccount, useContractRead } from "wagmi";

type Domain = {
  id: number;
  concatenated_text: string;
};

const Home: NextPage = () => {
  const [data, setData] = useState<Domain[] | null>(null);

  useEffect(() => {
    fetch("/api/domains")
      .then(response => response.json())
      .then(setData);
  }, []);
  console.log(data);

  const [formQuestion, setFormQuestion] = useState("");
  const [responseLanguage, setResponseLanguage] = useState("English");
  const [trigger, setTrigger] = useState(false);
  const [queryResult, setQueryResult] = useState<any>(null);

  const { address } = useAccount();

  const contractRead = useContractRead({
    address: "0xf90c831efeb6e228f836ca0ca3b78237d8b2bef2",
    abi: ERC1155ABI,
    functionName: "balanceOf",
    args: [address, 1],
  });

  const balance = parseInt(contractRead.data?.toString() || "0");
  console.log(balance, "balance");
  console.log(ERC1155ABI, contractRead.data?.toString(), "contractRead");

  const handleSubmit = (event: React.FormEvent) => {
    if (balance == 0) return alert("You need to own a Magic 8 Ball to ask a question!"), event.preventDefault();
    event.preventDefault();
    fetch("/api/query", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ question: formQuestion, language: responseLanguage }),
    })
      .then(response => response.json())
      .then(data => {
        setQueryResult(data);
        setTrigger(true);
      });
  };
  console.log(queryResult);

  return (
    <div className={styles.container}>
      <Head>
        <title>Magic 8 Ball </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Image src="/assets/frame.png" alt="8ball" width="1200" height="100" className={styles.backgroundImage} />
        <div className={styles.formContainer}>
          <form
            onSubmit={handleSubmit}
            style={{
              display: "flexBox",
              flexDirection: "column",
              position: "relative",
              zIndex: 1000,
            }}
          >
            <label htmlFor="query">Question:</label>
            <br />
            <input
              type="text"
              id="question"
              name="question"
              className={styles.inputField}
              value={formQuestion}
              onChange={event => setFormQuestion(event.target.value)}
              style={{ paddingBottom: "2%" }}
            />
            <br />
            <label htmlFor="query">Language:</label>
            <input
              type="text"
              id="language"
              name="language"
              className={styles.inputField}
              value={responseLanguage}
              onChange={event => setResponseLanguage(event.target.value)}
            />
            <br />
            <button type="submit" className={styles.submitButton}>
              Submit
            </button>
          </form>
        </div>

        <div className={styles.responseContainer}>
          <Eightballjs response={queryResult ? queryResult.text : "Thinking"} trigger={trigger} />
        </div>
      </main>
    </div>
  );
};
export default Home;
